### ISSUE TITLE
Issues with the `DUSE_CUDA` flag when not using GPU machine.

### ISSUE THREAD

**Issue by julesfowler** [milk-org/pyMilk#2]
In talking with @DasVinch, it sounds like this (`DUSE_CUDA`) flag is supposed to check you machine for a CUDA install, and leave you alone if you don't have GPUs. Tragically this isn't the case and when you go to install your `pyMilk` with `pip install -e .`, it throws an error searching for these environment variables. 

The quick hack was to comment out the `'DUSE_CUDA=ON'` line of cmake_args in the `build_extension()` func of the `setup.py` (line 45) but I assume there's a more sustainable fix.

**Comment by DasVinch** [comment]
Hopefully 1de4f9fdaf50d8c08e0ca1f284266d2b14f33e06 should fix that. Mahalo for reporting.
